import { UploadedDataset } from '../types';
import { processRowHierarchy } from './excelParser';

export const DEFAULT_DEMO_DATASET: UploadedDataset = {
  metadata: {
    id: 'demo-dataset-2026',
    fileName: 'Acompanhamento_Projetos_Marista.xlsx',
    uploadedAt: new Date().toISOString(),
    rowCount: 14,
    ondasCount: 2,
    avgProgress: 56,
    macroCount: 2,
    subitemCount: 12,
  },
  rows: processRowHierarchy([
    {
      id: 'demo-1',
      onda: 'ONDA 1',
      funcionalidade: '1. Preparação de Ambiente',
      inicioEstimativa: '2026-03-01',
      terminoEstimativa: '2026-03-10',
      etapa: 'Infraestrutura',
      porcentagem: 100,
      rawRowIndex: 2,
    },
    {
      id: 'demo-2',
      onda: 'ONDA 1',
      funcionalidade: '1.1 Setup do Servidor e Banco',
      inicioEstimativa: '2026-03-05',
      terminoEstimativa: '2026-03-15',
      etapa: 'Desenvolvimento',
      porcentagem: 100,
      rawRowIndex: 3,
    },
    {
      id: 'demo-3',
      onda: 'ONDA 1',
      funcionalidade: '1.2 Homologação do Ambiente',
      inicioEstimativa: '2026-03-12',
      terminoEstimativa: '2026-03-25',
      etapa: 'Homologação',
      porcentagem: 100,
      rawRowIndex: 4,
    },
    {
      id: 'demo-lh-parent',
      onda: 'ONDA 2',
      funcionalidade: '3. Login Híbrido',
      inicioEstimativa: '2026-04-01',
      terminoEstimativa: '2026-05-15',
      etapa: 'Desenvolvimento',
      porcentagem: 0,
      rawRowIndex: 5,
    },
    {
      id: 'demo-lh-3.1',
      onda: 'ONDA 2',
      funcionalidade: '3.1 Enviar Front-end (Sioux)',
      inicioEstimativa: '2026-04-01',
      terminoEstimativa: '2026-04-10',
      etapa: 'Front-end',
      porcentagem: 100,
      rawRowIndex: 6,
    },
    {
      id: 'demo-lh-3.1.1',
      onda: 'ONDA 2',
      funcionalidade: '3.1.1 Analisar Tecnicamente Front-end (Techne e Sioux)',
      inicioEstimativa: '2026-04-02',
      terminoEstimativa: '2026-04-08',
      etapa: 'Análise Técnica',
      porcentagem: 100,
      rawRowIndex: 7,
    },
    {
      id: 'demo-lh-3.1.2',
      onda: 'ONDA 2',
      funcionalidade: '3.1.2 Ajustar/Revisar Front-end (Techne)',
      inicioEstimativa: '2026-04-09',
      terminoEstimativa: '2026-04-15',
      etapa: 'Ajustes',
      porcentagem: 100,
      rawRowIndex: 8,
    },
    {
      id: 'demo-lh-3.2',
      onda: 'ONDA 2',
      funcionalidade: '3.2 Aprovar/Consolidar Regras de Negócio (Techne e Marista)',
      inicioEstimativa: '2026-04-10',
      terminoEstimativa: '2026-04-20',
      etapa: 'Negócio',
      porcentagem: 100,
      rawRowIndex: 9,
    },
    {
      id: 'demo-lh-3.1.3',
      onda: 'ONDA 2',
      funcionalidade: '3.1.3 Implementação do SSO (Techne)',
      inicioEstimativa: '2026-04-16',
      terminoEstimativa: '2026-04-28',
      etapa: 'Segurança',
      porcentagem: 50,
      rawRowIndex: 10,
    },
    {
      id: 'demo-lh-3.3',
      onda: 'ONDA 2',
      funcionalidade: '3.3 Desenvolver (Techne)',
      inicioEstimativa: '2026-04-20',
      terminoEstimativa: '2026-05-05',
      etapa: 'Desenvolvimento',
      porcentagem: 50,
      rawRowIndex: 11,
    },
    {
      id: 'demo-lh-3.4',
      onda: 'ONDA 2',
      funcionalidade: '3.4 Homologar (Techne e Marista)',
      inicioEstimativa: '2026-05-01',
      terminoEstimativa: '2026-05-10',
      etapa: 'Homologação',
      porcentagem: 0,
      rawRowIndex: 12,
    },
    {
      id: 'demo-lh-3.4.1',
      onda: 'ONDA 2',
      funcionalidade: '3.4.1 Ajustar Itens Após Homologação (Techne)',
      inicioEstimativa: '2026-05-08',
      terminoEstimativa: '2026-05-12',
      etapa: 'Ajustes',
      porcentagem: 0,
      rawRowIndex: 13,
    },
    {
      id: 'demo-lh-3.5',
      onda: 'ONDA 2',
      funcionalidade: '3.5 Enviar Termo de Aceite (Techne)',
      inicioEstimativa: '2026-05-12',
      terminoEstimativa: '2026-05-15',
      etapa: 'Aceite',
      porcentagem: 0,
      rawRowIndex: 14,
    },
  ]),
};
